Autoplay2
mgylabs/mkbot pull request #261
Opened 2023-10-20 10:24 UTC by minhyungk

## Summary of the Pull Request 

_Autoplay_ feature added to music command

## PR Checklist

- [x] Closes part of #28
- [x] [Changelog entry](https://github.com/mgylabs/mkbot/tree/main/changelogs)

### Testing

- [x] [Tested in packaged application](https://github.com/mgylabs/mkbot/wiki/How-to-Contribute#testing-in-packaged-application)

## Detailed Description of the Pull Request / Additional comments 
 - Autoplay function added

> `.play -auto song_name`
> When autoplay mode is on, next song will be automatically recommended according to youtube's 'next video' feature. 

> `.play -off`
> Turns off autoplay mode 

 - Skip command unnecessarily sending 'skipped ~' removed

Messages took up too much space

![image](https://github.com/mgylabs/mkbot/assets/70808710/d4126546-6fb7-48de-8203-f297bba6b918)

2023-10-21 08:11 UTC, MycroftKang commented
I think we can refactor the next function like this:

```py
@database.using_database
def next():    
   I18nExtension.set_current_locale_by_user(ctx.author.id)
   async def next_task():
       if len(guild_sl[gid].slist) <= guild_sl[gid].queue:
           await nextSong(gid, self.bot.user)
                  
       guild_sl[gid].queue += 1
       await self.playMusic(ctx)
            
   # if number of songs > queue num  
   if len(guild_sl[gid].slist) > guild_sl[gid].queue or guild_sl[gid].auto:
       fut = asyncio.run_coroutine_threadsafe(
             next_task(), self.bot.loop
       )
       fut.result()
```

2023-10-21 11:25 UTC, MycroftKang requested changes

2023-10-21 11:25 UTC, MycroftKang commented on src/bot/core/controllers/discord/music.py
> +    a = urlopen(song_url)
Also, it need to be change to aiohttp instead of urllib.

2023-10-26 17:32 UTC, minhyungk commented on src/bot/core/controllers/discord/music.py
> +    a = urlopen(song_url)
```Python
async def nextSong(gid, bot):
    # fetch next song from yt, then return as Song

    song_url = guild_sl[gid].songPlaying().url

    async def open_song():
        async with aiohttp.ClientSession() as session:
            async with session.get(song_url) as resp:
                soup = BeautifulSoup(await resp.read(), "lxml")
                b = soup.find_all("script")[-5]
                J1 = str(b).split("var ytInitialData = ")
                u = J1[1].find("url")
                next_url = "https://youtube.com" + J1[1][u + 6 : u + 26]
        return next_url
```

Resolved

2023-10-26 22:32 UTC, MycroftKang approved these changes

2023-10-26 22:33 UTC, merged